---
- name: elasticsearch container
  docker:
    name: elasticsearch
    image: elasticsearch:2.1
    state: started
    volumes:
      - "{{ role_path }}/files/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports: 
    - "9200:9200"
    - "9300:9300"
