---
- name: kibana container
  docker:
    name: kibana
    image: "kibana:4.2"
    state: started
    volumes:
    - "{{ role_path }}/files:/opt/kibana/config"
    ports:  
    - "5601:5601"
    links:
    - elasticsearch

